[programs.localnet]
example="HmZ5eqwP6CT6XUSFq2J39o4jfRJk91rHPSKnZqzBFsLx"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
